import numpy as np

# General Environment Settings
MAX_AIRCRAFT = 3
MAX_FLIGHTS_PER_AIRCRAFT = 17
ROWS_STATE_SPACE = 1 + MAX_AIRCRAFT

# Time-based state space calculation for matrix-based approach (SSF)
# Maximum recovery period: 24 hours (1440 minutes) converted to 15-minute intervals
MAX_RECOVERY_HOURS = 24
MAX_RECOVERY_INTERVALS = (MAX_RECOVERY_HOURS * 60) // 15
MAX_TIME_INTERVALS = MAX_RECOVERY_INTERVALS
COLUMNS_STATE_SPACE = MAX_TIME_INTERVALS

# Number of possible actions (+1 for the zero for no action and cancellations)
ACTION_SPACE_SIZE = (MAX_AIRCRAFT + 1) * (MAX_FLIGHTS_PER_AIRCRAFT + 1)

DEPARTURE_AFTER_END_RECOVERY = 2

TIMESTEP_HOURS = 1

DUMMY_VALUE = -999

# PENALTIES for the calculation of the reward (def _calculate_reward in environment_ssf.py and environment_ssf_large_dimensions.py)
RESOLVED_CONFLICT_REWARD = 10
DELAY_MINUTE_PENALTY = 0.0001
DELAY_PENALTY_THRESHOLD_MINUTES = 300
MAX_DELAY_PENALTY = 25000
CANCELLED_FLIGHT_PENALTY = 1
NO_ACTION_PENALTY = 1
AHEAD_PENALTY = 0.1
TIME_MINUTE_PENALTY = 0.00005
AUTOMATIC_CANCELLATION_PENALTY = 1

PROBABILITY_RESOLUTION_BONUS_SCALE = 10
LOW_CONFIDENCE_ACTION_THRESHOLD = 0.4
LOW_CONFIDENCE_ACTION_PENALTY = 0.5

# PENALTY ENABLED FLAGS (for debugging/verification)
PENALTY_1_DELAY_ENABLED = True
PENALTY_2_CANCELLATION_ENABLED = True
PENALTY_3_INACTION_ENABLED = True
PENALTY_4_PROACTIVE_ENABLED = False
PENALTY_5_TIME_ENABLED = True
PENALTY_6_FINAL_REWARD_ENABLED = True
PENALTY_7_AUTO_CANCELLATION_ENABLED = True
PENALTY_8_PROBABILITY_RESOLUTION_BONUS_ENABLED = True
PENALTY_9_LOW_CONFIDENCE_ACTION_ENABLED = True

# FEATURE ENGINEERING / TEMPORAL CONTEXT SETTINGS
ENABLE_TEMPORAL_DERIVED_FEATURES = True
DERIVED_FEATURES_PER_AIRCRAFT = 4
OBS_STACK_SIZE = 2
STACKING_PADDING_VALUE = 0.0

# OTHER SETTINGS
MIN_TURN_TIME = 0
MIN_BREAKDOWN_PROBABILITY = 0

# DEBUGGING SETTINGS
DEBUG_MODE = False
DEBUG_MODE_TRAINING = False
DEBUG_MODE_REWARD = False
DEBUG_MODE_PRINT_STATE = False
DEBUG_MODE_CANCELLED_FLIGHT = False
DEBUG_MODE_VISUALIZATION = False
DEBUG_MODE_BREAKDOWN = False
DEBUG_MODE_ACTION = False
DEBUG_MODE_STOPPING_CRITERIA = False
DEBUG_MODE_SCHEDULING = False
DEBUG_MODE_REWARD_LAST_MINUTE_PENALTY = False
DEBUG_MODE_REWARD_RESOLVED_CONFLICTS = False
DEBUG_MODE_DELAY_MINUTES = False
DEBUG_MODE_ACTION_EVALUATION = False
